labels/urls.py
from django.urls import path

from labels import views

urlpatterns = [
    path("", views.LabelsListView.as_view(), name="all_labels"),
    path("create/", views.LabelCreateView.as_view(), name="label_create"),
    path(
        "<int:pk>/update/", views.LabelEditView.as_view(), name="label_update"
    ),  # noqa E501
    path(
        "<int:pk>/delete/", views.LabelDeleteView.as_view(), name="label_delete"
    ),  # noqa E501
]

app_name = "labels"

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("statuses/", include("statuses.urls", namespace="statuses")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("labels/", include("labels.urls", namespace="labels")),
]

tasks/urls.py
from django.urls import path

from tasks import views


urlpatterns = [
    path("", views.TasksListView.as_view(), name="tasks"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="task_show"),
    path("create/", views.TaskCreateView.as_view(), name="task_create"),
    path("<int:pk>/update/", views.TaskEditView.as_view(), name="task_update"),
    path(
        "<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"
    ),  # noqa E501
]

app_name = "tasks"

labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(
        max_length=150, unique=True, blank=False, verbose_name=_("Name")
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Creation date")
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Label")
        verbose_name_plural = _("Labels")

labels/forms.py
from django import forms
from django.utils.translation import gettext as _

from labels import models


class LabelForm(forms.ModelForm):
    name = forms.CharField(
        label=_("Name"),
        max_length=150,
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-input form-control", "placeholder": _("Name")}
        ),
    )

    class Meta:
        model = models.Label
        fields = ("name",)

labels/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.utils.translation import gettext_lazy as _
from django.contrib.messages.views import SuccessMessageMixin

from labels.forms import LabelForm
from labels.models import Label
from task_manager.mixins import AuthRequiredMixin, DeleteProtectionMixin


class LabelsListView(AuthRequiredMixin, ListView):
    """
    Show all labels.

    Authorisation required.
    """

    template_name = "labels/labels.html"
    model = Label
    context_object_name = "labels"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["current_page"] = "labels"
        return context


class LabelCreateView(AuthRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Create new label.

    Authorisation required.
    """

    template_name = "labels/labels_form.html"
    model = Label
    form_class = LabelForm
    success_url = reverse_lazy("labels:all_labels")
    success_message = _("Label successfully created")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Create")
        context["current_page"] = "labels"
        return context


class LabelEditView(AuthRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Edit existing label.

    Authorisation required.
    """

    template_name = "labels/labels_form.html"
    model = Label
    form_class = LabelForm
    success_url = reverse_lazy("labels:all_labels")
    success_message = _("Label successfully changed")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Change label")
        context["current_page"] = "labels"
        return context


class LabelDeleteView(
    AuthRequiredMixin, DeleteProtectionMixin, SuccessMessageMixin, DeleteView
):
    """
    Delete existing label.

    Authorization required.
    If the label is associated with at least one task it cannot be deleted.
    """

    template_name = "labels/delete.html"
    model = Label
    success_url = reverse_lazy("labels:all_labels")
    success_message = _("Label successfully deleted")
    protected_message = _(
        "It is not possible to delete a label " "because it is in use"
    )
    protected_url = reverse_lazy("labels:all_labels")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Yes, delete")
        context["current_page"] = "labels"
        return context

labels/templates/labels/delete.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
    <h1 class="my-4">{{ title }}</h1>

    <form method="post">
        <p>{% trans 'Are you sure you want to delete' %} {{ label.name }}?</p>
        {% csrf_token %}
        {% bootstrap_button button_text button_type="submit" button_class="btn btn-danger" %}
    </form>
{% endblock %}

labels/templates/labels/labels.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}


{% block content %}
    <h1 class="my-4">{{ title }}</h1>

    <a class="btn btn-primary mb-3" href="{% url 'labels:label_create' %}">{% trans 'Create label' %}</a>

    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>{% trans 'Name' %}</th>
                <th>{% trans 'Creation date' %}</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            {% if labels %}
                {% for label in labels %}
                    <tr>
                        <td>{{ label.id }}</td>
                        <td>{{ label.name }}</td>
                        <td>{{ label.created_at }}</td>
                        <td>
                          <a href="{% url 'labels:label_update' label.id %}">{% trans 'Update' %}</a>
                          <br>
                          <a href="{% url 'labels:label_delete' label.id %}">{% trans 'Delete' %}</a>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
{% endblock content %}

labels/templates/labels/labels_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
    <h1 class="my-4">{% trans 'labels' %}</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <div class="mb-3">
                <label class="form-label" for="{{ f.id_for_label }}">{{f.label}} </label>
                {{ f }}
            </div>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        {% bootstrap_button button_text button_type="submit" button_class="btn btn-primary btn-lg" %}
    </form>
{% endblock %}