statuses/urls.py
from django.urls import path

from statuses import views

urlpatterns = [
    path("", views.StatusesListView.as_view(), name="all_statuses"),
    path("create/", views.StatusCreateView.as_view(), name="status_create"),
    path(
        "<int:pk>/update/", views.StatusUpdateView.as_view(), name="status_update"
    ),  # noqa E501
    path(
        "<int:pk>/delete/", views.StatusDeleteView.as_view(), name="status_delete"
    ),  # noqa E501
]

app_name = "statuses"

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("statuses/", include("statuses.urls", namespace="statuses")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("labels/", include("labels.urls", namespace="labels")),
]

tasks/urls.py
from django.urls import path

from tasks import views


urlpatterns = [
    path("", views.TasksListView.as_view(), name="tasks"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="task_show"),
    path("create/", views.TaskCreateView.as_view(), name="task_create"),
    path("<int:pk>/update/", views.TaskEditView.as_view(), name="task_update"),
    path(
        "<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"
    ),  # noqa E501
]

app_name = "tasks"

statuses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Status(models.Model):
    name = models.CharField(
        max_length=150,
        unique=True,
        blank=False,
        verbose_name=_("Name"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Creation date")
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Status")
        verbose_name_plural = _("Statuses")

statuses/forms.py
from django import forms
from django.utils.translation import gettext as _

from statuses import models


class StatusForm(forms.ModelForm):
    name = forms.CharField(
        label=_("Name"),
        max_length=150,
        required=True,
        widget=forms.TextInput(
            attrs={"class": "form-input form-control", "placeholder": _("Name")}
        ),
    )

    class Meta:
        model = models.Status
        fields = [
            "name",
        ]

statuses/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.translation import gettext_lazy as _
from django.contrib.messages.views import SuccessMessageMixin

from statuses.forms import StatusForm
from statuses.models import Status
from task_manager.mixins import AuthRequiredMixin, DeleteProtectionMixin


class StatusesListView(AuthRequiredMixin, ListView):
    template_name = "statuses/statuses.html"
    model = Status
    context_object_name = "statuses"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["current_page"] = "statuses"
        return context


class StatusCreateView(AuthRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "statuses/statuses_form.html"
    model = Status
    form_class = StatusForm
    success_url = reverse_lazy("statuses:all_statuses")
    success_message = _("Status successfully created")

    # def get_success_url(self):
    #     return reverse_lazy('all_statuses')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Create")
        context["current_page"] = "statuses"
        return context


class StatusUpdateView(AuthRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = "statuses/statuses_form.html"
    model = Status
    form_class = StatusForm
    success_url = reverse_lazy("statuses:all_statuses")
    success_message = _("Status successfully changed")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Change")
        context["current_page"] = "statuses"
        return context


class StatusDeleteView(
    AuthRequiredMixin, DeleteProtectionMixin, SuccessMessageMixin, DeleteView
):
    template_name = "statuses/delete.html"
    model = Status
    success_url = reverse_lazy("statuses:all_statuses")
    success_message = _("Status successfully deleted")
    protected_message = _(
        "It is not possible to delete a status " "because it is in use"
    )
    protected_url = reverse_lazy("statuses:all_statuses")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Yes, delete")
        context["current_page"] = "statuses"
        return context

statuses/templates/statuses/delete.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}


{% block content %}
    <h1 class="my-4">{{ title }}</h1>

    <form method="post">
        <p>{% trans 'Are you sure you want to delete' %} {{ status.name }}?</p>
        {% csrf_token %}
        {% bootstrap_button button_text button_type="submit" button_class="btn btn-danger" %}
    </form>
{% endblock %}

statuses/templates/statuses/statuses.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}


{% block content %}
    <h1 class="my-4">{% trans 'statuses' %}</h1>

    <a class="btn btn-primary" href="{% url 'statuses:status_create' %}">{% trans 'Create status' %}</a>

    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>{% trans 'Name' %}</th>
                <th>{% trans 'Creation date' %}</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            {% if statuses %}
                {% for status in statuses %}
                    <tr>
                        <td>{{ status.id }}</td>
                        <td>{{ status.name }}</td>
                        <td>{{ status.created_at }}</td>
                        <td>
                          <a href="{% url 'statuses:status_update' status.id %}">{% trans 'Update' %}</a>
                          <br>
                          <a href="{% url 'statuses:status_delete' status.id %}">{% trans 'Delete' %}</a>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
{% endblock %}

statuses/templates/statuses/statuses_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
    <h1 class="my-4">{% trans 'statuses' %}</h1>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <div class="mb-3">
                <label class="form-label" for="{{ f.id_for_label }}">{{f.label}} </label>
                {{ f }}
            </div>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        {% bootstrap_button button_text button_type="submit" button_class="btn btn-primary btn-lg" %}
    </form>
{% endblock %}