task_manager/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("statuses/", include("statuses.urls", namespace="statuses")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("labels/", include("labels.urls", namespace="labels")),
]

tasks/urls.py
from django.urls import path

from tasks import views


urlpatterns = [
    path("", views.TasksListView.as_view(), name="tasks"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="task_show"),
    path("create/", views.TaskCreateView.as_view(), name="task_create"),
    path("<int:pk>/update/", views.TaskEditView.as_view(), name="task_update"),
    path(
        "<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"
    ),  # noqa E501
]

app_name = "tasks"

tasks/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from labels.models import Label
from users.models import User
from statuses.models import Status

# from labels.models import Label


class TimestampedModel(models.Model):
    """An abstract model with a pair of timestamps."""

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Creation date")
    )
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_("Date to update"))

    class Meta:
        abstract = True


class Task(TimestampedModel):
    name = models.CharField(
        max_length=150, unique=True, blank=False, verbose_name=_("Name")
    )
    description = models.TextField(
        max_length=10000, unique=True, blank=True, verbose_name=_("Description")
    )
    author = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="author", verbose_name=_("Author")
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        related_name="statuses",
        verbose_name=_("Status"),
    )
    executor = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.PROTECT,
        related_name="executor",
        verbose_name=_("Executor"),
    )

    labels = models.ManyToManyField(
        Label,
        through="TaskLabelRelation",
        through_fields=("task", "label"),
        blank=True,
        related_name="labels",
        verbose_name=_("Labels"),
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Task")
        verbose_name_plural = _("Tasks")


class TaskLabelRelation(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.PROTECT)

tasks/forms.py
from django import forms

from tasks import models


class TaskForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ["name", "description", "status", "executor", "labels"]

tasks/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.utils.translation import gettext_lazy as _
from django.contrib.messages.views import SuccessMessageMixin
from django_filters.views import FilterView

from task_manager.mixins import AuthRequiredMixin, AuthorDeletionMixin
from users.models import User
from tasks.models import Task
from tasks.forms import TaskForm
from tasks.filters import TaskFilter


class TasksListView(AuthRequiredMixin, FilterView):
    """
    Show all tasks.

    Authorisation required.
    """

    template_name = "tasks/tasks.html"
    model = Task
    filterset_class = TaskFilter
    context_object_name = "tasks"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Show")
        context["current_page"] = "tasks"
        context["user"] = self.request.user
        return context


class TaskDetailView(AuthRequiredMixin, DetailView):
    """
    Show one task details.

    Authorisation required.
    """

    template_name = "tasks/task_detail.html"
    model = Task
    context_object_name = "task"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["current_page"] = "tasks"
        return context


class TaskCreateView(AuthRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Create new task.

    Authorisation required.
    """

    template_name = "tasks/tasks_form.html"
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:tasks")
    success_message = _("Task successfully created")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Create")
        context["current_page"] = "tasks"
        return context

    def form_valid(self, form):
        """
        Set current user as the task's author.
        """
        user = self.request.user
        form.instance.author = User.objects.get(pk=user.pk)
        return super().form_valid(form)


class TaskEditView(AuthRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Edit existing task.

    Authorisation required.
    """

    template_name = "tasks/tasks_form.html"
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:tasks")
    success_message = _("Task successfully changed")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Change")
        context["current_page"] = "tasks"
        return context


class TaskDeleteView(
    AuthRequiredMixin, AuthorDeletionMixin, SuccessMessageMixin, DeleteView
):
    """
    Delete existing task.

    Authorization required.
    Only the author can delete his tasks.
    """

    template_name = "tasks/delete.html"
    model = Task
    success_url = reverse_lazy("tasks:tasks")
    success_message = _("Task successfully deleted")
    author_message = _("The task can be deleted only by its author")
    author_url = reverse_lazy("tasks:tasks")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["button_text"] = _("Yes, delete")
        context["current_page"] = "tasks"
        return context

tasks/templates/tasks/delete.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
    <h1 class="my-4">{{ title }}</h1>

    <form method="post">
        <p>{% trans 'Are you sure you want to delete' %} {{ task.name }}?</p>
        {% csrf_token %}
        {% bootstrap_button button_text button_type="submit" button_class="btn btn-danger" %}
    </form>
{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
    <h1 class="my-4">{{ title }}</h1>

    <div class="card">
        <div class="card-header bg-secondary text-white">
            <h2>{{ task.name }}</h2>
        </div>

        <div class="card-body bg-light">
            <p>{{ task.description }}</p>

            <hr>

            <div class="container">

                <div class="row p-1">
                    <div class="col">{% trans 'Author' %}</div>
                    <div class="col">{{ task.author }}</div>
                </div>

                <div class="row p-1">
                    <div class="col">{% trans 'Executor' %}</div>
                    <div class="col">{{ task.executor }}</div>
                </div>

                <div class="row p-1">
                    <div class="col">{% trans 'Status' %}</div>
                    <div class="col">{{ task.status }}</div>
                </div>

                <div class="row p-1">
                    <div class="col">{% trans 'Creation date' %}</div>
                    <div class="col">{{ task.created_at }}</div>
                </div>

                <div class="row p-1">
                    <div class="col">
                        <h6>{% trans 'Labels' %}:</h6>
                        <ul>
                            {% for label in task.labels.all %}
                                <li>{{  label.name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div class="row p-1">
                    <div class="col">
                        <a href="{% url 'tasks:task_update' task.id %}">{% trans 'Update' %}</a>
                        <br>
                        <a href="{% url 'tasks:task_delete' task.id %}">{% trans 'Delete' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

tasks/templates/tasks/tasks.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
    <h1 class="my-4">{{ title }}</h1>

    <a class="btn btn-primary mb-3" href="{% url 'tasks:task_create' %}">{% trans 'Create task' %}</a>

    <div class="card mb-3">
        <div class="card-body bg-light">
            <form class="form-inline center" method="get">
              {% bootstrap_form filter.form field_class="ml-2 mr-3" %}
              {% bootstrap_button button_text button_type="submit" button_class="btn btn-primary" %}
            </form>
        </div>
    </div>

    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>{% trans 'Name' %}</th>
                <th>{% trans 'Status' %}</th>
                <th>{% trans 'Author' %}</th>
                <th>{% trans 'Executor' %}</th>
                <th>{% trans 'Creation date' %}</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            {% if tasks %}
                {% for task in tasks %}
                    <tr>
                        <td>{{ task.id }}</td>
                        <td><a href="{% url 'tasks:task_show' task.id %}">{{ task.name }}</a></td>
                        <td>{{ task.status }}</td>
                        <td>{{ task.author.fullname }}</td>
                        <td>{{ task.executor.fullname }}</td>
                        <td>{{ task.created_at }}</td>
                        <td>
                            <a href="{% url 'tasks:task_update' task.id %}">{% trans 'Update' %}</a>
                            <br>
                            <a href="{% url 'tasks:task_delete' task.id %}">{% trans 'Delete' %}</a>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
{% endblock content %}

tasks/templates/tasks/tasks_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
    <h1 class="my-4">{% trans 'tasks' %}</h1>
    <form method="post" class="mb-4">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <div class="form-error">{{ form.non_field_errors }}</div>
            {% bootstrap_form form %}
            <div class="form-error">{{ f.errors }}</div>
        {% bootstrap_button button_text button_type="submit" button_class="btn btn-primary btn-lg" %}
    </form>
{% endblock %}