labels/urls.py
from django.urls import path

from labels import views

urlpatterns = [
    path("", views.LabelsListView.as_view(), name="all_labels"),
    path("create/", views.LabelCreateView.as_view(), name="label_create"),
    path(
        "<int:pk>/update/", views.LabelEditView.as_view(), name="label_update"
    ),  # noqa E501
    path(
        "<int:pk>/delete/", views.LabelDeleteView.as_view(), name="label_delete"
    ),  # noqa E501
]

app_name = "labels"

manager/urls.py
from django.urls import path
from manager import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.LogoutUser.as_view(), name="logout"),
]

statuses/urls.py
from django.urls import path

from statuses import views

urlpatterns = [
    path("", views.StatusesListView.as_view(), name="all_statuses"),
    path("create/", views.StatusCreateView.as_view(), name="status_create"),
    path(
        "<int:pk>/update/", views.StatusUpdateView.as_view(), name="status_update"
    ),  # noqa E501
    path(
        "<int:pk>/delete/", views.StatusDeleteView.as_view(), name="status_delete"
    ),  # noqa E501
]

app_name = "statuses"

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("statuses/", include("statuses.urls", namespace="statuses")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("labels/", include("labels.urls", namespace="labels")),
]

tasks/urls.py
from django.urls import path

from tasks import views


urlpatterns = [
    path("", views.TasksListView.as_view(), name="tasks"),
    path("<int:pk>/", views.TaskDetailView.as_view(), name="task_show"),
    path("create/", views.TaskCreateView.as_view(), name="task_create"),
    path("<int:pk>/update/", views.TaskEditView.as_view(), name="task_update"),
    path(
        "<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"
    ),  # noqa E501
]

app_name = "tasks"

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path("", views.UsersIndexView.as_view(), name="users_index"),
    path("create/", views.RegisterUser.as_view(), name="register"),
    path("create/done", views.RegisterDone.as_view(), name="register_done"),
    path("<int:pk>/update/", views.UserEditView.as_view(), name="edit_user"),
    path(
        "<int:pk>/delete/", views.UserDeleteView.as_view(), name="delete_user"
    ),  # noqa E501

]

app_name = "users"

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext as _
from users import models


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label=_("username"),
        widget=forms.TextInput(
            attrs={"class": "form-input form-control", "placeholder": _("username")}
        ),
    )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(
            attrs={"class": "form-input form-control", "placeholder": _("Password")}
        ),
    )

    class Meta:
        model = models.User
        fields = ["username", "password"]

manager/views.py
from django.utils.translation import gettext as _
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from manager.forms import LoginUserForm


# Create your views here.
class IndexView(TemplateView):
    template_name = "manager/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["logo"] = _("Task Manager")
        context["title"] = _("Task Manager")
        context["current_page"] = "index"
        context["user"] = self.request.user
        return context


class LoginUser(SuccessMessageMixin, LoginView):
    form_class = LoginUserForm
    template_name = "manager/login.html"
    next_page = reverse_lazy("index")
    success_message = _("You are logged in")
    extra_context = {
        "title": _("Task Manager"),
        "logo": _("Task Manager"),
        "button_text": _("Enter"),
        "current_page": "login",
    }


class LogoutUser(LogoutView):
    next_page = reverse_lazy("index")
    success_message = _("You are logged out")

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, _("You are logged out"))
        return super().dispatch(request, *args, **kwargs)

manager/templates/manager/components/footer.html
<footer class="p-3 text-bg-dark">
    <div class="container my-5 pt-4 border-top">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none" previewlistener="true">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 ">
          <li><a target="_blank" href="https://ru.hexlet.io"  previewlistener="true" class="nav-link px-2 text-white">hexlet</a></li>
        </ul>

      </div>
    </div>
  </footer>

manager/templates/manager/components/header.html
{% load i18n %}

<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex  mb-2 mb-lg-0 text-white text-decoration-none" previewlistener="true">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>

            <a class="navbar-brand fs-4 me-5" href="/" previewlistener="true">{{ logo }}</a>
            <ul class=" nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li>
                    <a href="{% url 'users:users_index' %}"
                       class="nav-link px-2 {% if current_page == 'users_index' %}text-secondary {% else %} text-white {% endif %}">
                        {% trans "Users" %}</a>
                </li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'statuses:all_statuses' %}"
                       class="nav-link px-2 {% if current_page == 'statuses' %}text-secondary {% else %} text-white {% endif %}">{% trans "Statuses" %}</a></li>
                <li><a href="{% url 'labels:all_labels' %}"
                       class="nav-link px-2 {% if current_page == 'labels' %}text-secondary {% else %} text-white {% endif %}">{% trans "Tags" %}</a></li>
                <li><a href="{% url 'tasks:tasks' %}"
                       class="nav-link px-2 {% if current_page == 'tasks' %}text-secondary {% else %} text-white {% endif %}">{% trans "Tasks" %}</a></li>
                {% endif %}
                </ul>

                {% if not user.is_authenticated %}
                <div class="text-end">
                    <a href="{% url 'login' %}" class="btn btn-outline-light me-2">{% trans "login" %}</a>
                    <a href="{% url 'users:register' %}" class="btn btn-warning">{% trans "sigh up" %}</a>
                </div>
                {% else %}
                <div class="text-end text-white fw-bold">
                     {% trans 'Hello' %}, {{ user.username }} |
                </div>
                <ul class=" nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'logout' %}" class="nav-link px-2 text-white">{% trans ' logout' %}</a></li>
                </ul>
                {% endif %}
        </div>
    </div>
</header>